name: react-antd-aspnetcore-module

trigger:
- master
- release/*

pool:
  vmImage: 'windows-latest'

steps:
- checkout: self
  submodules: 'recursive'
- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: RAANC.Module.nuspec

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: nuget.org
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'))
