name: react-antd-aspnetcore-app

trigger:
- master
- release/*

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetCommand@2
  displayName: 'NuGet pack'
  inputs:
    command: pack
    packagesToPack: app/JBuschke.Glue.Starter.nuspec

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: nuget.org
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'))
